services:
  app:
    build:
      context: .
    container_name: splitwise-clone
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: splitwise-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - './data:/var/lib/postgresql/data'
      - './dumps:/dumps'
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: splitwise-redis
    restart: always
    ports:
      - '6379:6379'
